name: btc_pay_repository
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  btc_pay_api:
    path: ../btc_pay_api
  domain_models:
    path: ../domain_models

dev_dependencies: 
  lints: ^2.0.1
  test: ^1.23.1

