name: user_repository
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  domain_models:
    path: ../domain_models
  user_local_storage:
    path: ../user_local_storage

dev_dependencies: 
  lints: ^2.0.1
  test: ^1.23.1