name: btc_pay_api
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dio: ^5.0.1
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  test: ^1.22.0
  lints: ^2.0.1